# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_hrn_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_hrn_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_usd_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_usd_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
