# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_analyzer', '0002_auto_20171105_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopwordlist',
            options={'verbose_name': 'Stop Word'},
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_disable_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stopwordlist',
            name='word',
            field=models.CharField(max_length=50, unique=True, verbose_name='слово'),
        ),
    ]
