# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='currency',
            field=models.CharField(blank=True, max_length=20, verbose_name='Carrency'),
        ),
    ]
