# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collections_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='email_is_send',
            field=models.BooleanField(default=False, verbose_name='Email is send'),
        ),
        migrations.AddField(
            model_name='collections',
            name='phones',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
