# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170923_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='donor',
            field=models.CharField(choices=[('olx', 'olx'), ('auto.ria', 'auto.ria'), ('rst.ua', 'rst.ua')], max_length=50, verbose_name='Site donor'),
        ),
    ]
