# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20171120_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='donor',
            field=models.CharField(choices=[('olx', 'olx'), ('auto.ria', 'auto.ria'), ('rst.ua', 'rst.ua'), ('avtobazar.infocar.ua', 'avtobazar.infocar.ua')], max_length=50, verbose_name='Site donor'),
        ),
    ]
